version: 2

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: yaml2env
    main: .
    binary: yaml2env
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: yaml2env
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha256

release:
  github:
    owner: huberp
    name: yaml2env
  draft: false
  prerelease: auto
  mode: append
  header: |
    ## Release {{ .Tag }}
    
    Download the appropriate binary for your platform below.
  footer: |
    **Full Changelog**: https://github.com/huberp/yaml2env/compare/{{ .PreviousTag }}...{{ .Tag }}

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
      - Merge pull request
      - Merge branch

snapshot:
  version_template: "{{ .Version }}-next"
