name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25.3'
    
    - name: Run tests
      run: go test -v ./...
    
    - name: Build binaries
      run: |
        # Linux AMD64
        GOOS=linux GOARCH=amd64 go build -ldflags "-X main.version=${{ github.ref_name }} -X main.commit=${{ github.sha }} -X main.date=$(date -u +%Y-%m-%dT%H:%M:%SZ)" -o yaml2env-linux-amd64
        
        # Linux ARM64
        GOOS=linux GOARCH=arm64 go build -ldflags "-X main.version=${{ github.ref_name }} -X main.commit=${{ github.sha }} -X main.date=$(date -u +%Y-%m-%dT%H:%M:%SZ)" -o yaml2env-linux-arm64
        
        # Windows AMD64
        GOOS=windows GOARCH=amd64 go build -ldflags "-X main.version=${{ github.ref_name }} -X main.commit=${{ github.sha }} -X main.date=$(date -u +%Y-%m-%dT%H:%M:%SZ)" -o yaml2env-windows-amd64.exe
        
        # Windows ARM64
        GOOS=windows GOARCH=arm64 go build -ldflags "-X main.version=${{ github.ref_name }} -X main.commit=${{ github.sha }} -X main.date=$(date -u +%Y-%m-%dT%H:%M:%SZ)" -o yaml2env-windows-arm64.exe
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          yaml2env-linux-amd64
          yaml2env-linux-arm64
          yaml2env-windows-amd64.exe
          yaml2env-windows-arm64.exe
        generate_release_notes: true
